name: IOPS-AssetScrapper-InteropRegistry

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  job1:
    name: AssetScrapper Interoperability Registry
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
          
      - uses: actions/checkout@v4
        with:
          repository: NHSDigital/FHIR-R4-UKCORE-STAGING-MAIN
          path: FHIR-R4-UKCORE-STAGING-MAIN

      - uses: actions/checkout@v4
        with:
          repository: NHSDigital/NHSEngland-FHIR-ImplementationGuide
          path: NHSEngland-FHIR-ImplementationGuide

      - uses: actions/checkout@v4
        with:
          repository: NHSDigital/NHSEngland-FHIR-Programme-ImplementationGuide
          path: NHSEngland-FHIR-Programme-ImplementationGuide
      
      - uses: actions/checkout@v4
        with:
          repository: NHSDigital/FHIR-R4-UKCORE-COMMUNITYASSETS
          path: FHIR-R4-UKCORE-COMMUNITYASSETS
            
      - uses: actions/checkout@v4
        with:
          repository: NHSDigital/NHSDigital-FHIR-Medicines-ImplementationGuide
          path: NHSDigital-FHIR-Medicines-ImplementationGuide
      
      - uses: actions/checkout@v4
        with:
          repository: NHSDigital/FHIR-R4-CLINICAL-OBSERVATIONS
          path: FHIR-R4-CLINICAL-OBSERVATIONS
      
      - uses: actions/checkout@v4
        with:
          repository: NHSDigital/NHSDigital-FHIR-BookingAndReferrals
          path: NHSDigital-FHIR-BookingAndReferrals
      
      - uses: actions/checkout@v4
        with:
          repository: NHSDigital/NHSDigital-FHIR-Genomics-ImplementationGuide
          path: NHSDigital-FHIR-Genomics-ImplementationGuide
          
      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run guide scaper
        run: python guide_requests.py
       
      - name: Run asset scraper
        run: |
          python asset_scraper.py

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          add: '.'
    
